[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_21 = "GBRnGhaM3cU1KHbK15nHNAFoFxJYSX1mubeeD9ds7B8s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mattkrak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
