[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_21b = "Aktnrif6isEN3DiQ18de7KZbTPM1WwkjwcMtced7uSWX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mattkrak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
