[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_17 = "E4QFEcHGagrBCwJzQsTXn8i5wMuVqMGGuw8PS23o2ZBq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mattkrak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
