[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_16 = "GhmS32KJtwbC622Mhv16e94hVVHUWFjsV7khTxmwBx67"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mattkrak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
