[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_6 = "4s9fdUYmAGBB8cMKw5KUpedViuRrLNBTyL7KY9euw9cr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mattkrak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
